[package]
name = "nyvo-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
zip = ["dep:zip", "dep:nt-time"]
nyvo = []


[dependencies]
chrono = "0.4.44"
dh = "0.10.0"
nt-time = { version = "0.15.0", features = ["chrono"], optional = true }
thiserror = "2.0.18"
zip = { version = "8.5.1", default-features = false, features = [
  "chrono",
  "nt-time",
], optional = true }
